# Generated by Django 4.0.6 on 2022-07-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('established_at', models.DateTimeField()),
                ('city', models.CharField(max_length=128)),
            ],
        ),
    ]
