# Generated by Django 4.0.6 on 2022-08-01 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=9999, on_delete=django.db.models.deletion.CASCADE, to='store.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.CharField(max_length=5),
        ),
    ]
