# Generated by Django 4.0.6 on 2022-08-01 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_brand_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=9999, on_delete=django.db.models.deletion.CASCADE, to='store.brand'),
        ),
    ]
