# Generated by Django 4.0.6 on 2022-07-31 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0002_alter_brand_established_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='established_at',
            field=models.PositiveIntegerField(),
        ),
    ]
