# Generated by Django 4.0.6 on 2022-08-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='established_at',
            field=models.DateField(),
        ),
    ]
