# Generated by Django 4.0.6 on 2022-07-31 12:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brands",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the brand", max_length=60, unique=True
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Description of the brand", max_length=255
                    ),
                ),
                (
                    "established_at",
                    models.DateTimeField(help_text="Established brand date"),
                ),
                (
                    "city",
                    models.CharField(help_text="City of the brand", max_length=30),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the product", max_length=60),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Description of the product", max_length=255
                    ),
                ),
                (
                    "image_url",
                    models.URLField(help_text="Image URL of the product", null=True),
                ),
                (
                    "price",
                    models.FloatField(
                        help_text="Price of the product",
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.0, message="Price must be bigger than 0.0"
                            )
                        ],
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(default=0, help_text="Quantity of the product"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="Whether the product is active"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.brands",
                    ),
                ),
            ],
        ),
    ]
